server:
  port: 8891


#############################################################################################
#############################################################################################
################Redis哨兵模式配置##############################################################
# redis配置信息
spring:
  redis:
    ###################以下为redis单机模式配置###########################
    host: 47.95.142.79    # Redis服务器地址
    port: 6379         # Redis服务器连接端口
    database: 0        # Redis数据库索引（默认为0）
    #password: 123456   # Redis服务器连接密码（默认为空）
    #timeout: 3000      # 连接超时时间（毫秒）
    ###################以下为redis哨兵增加的配置###########################
    password:    # Redis服务器连接密码（默认为空）
    timeout: 3000      # 连接超时时间（毫秒）
    sentinel:
      nodes: 47.95.142.79:26379,47.95.142.79:26380,47.95.142.79:26381 # 集群哨兵节点配置，多个节点之间用英文逗号分割
      master: mymaster # Redis主节点名称，哨兵配置文件中的名称
################Redis哨兵模式配置##############################################################
#############################################################################################
#############################################################################################
