server:
  port: 8892


#############################################################################################
#############################################################################################
################Redis集群模式配置##############################################################
# redis配置信息
spring:
  redis:
    timeout: 6000
    password: 123456
    cluster:
      nodes: 47.95.142.79:6379,47.95.142.79:6380,47.95.142.79:6381,47.95.142.79:6389,47.95.142.79:6390,47.95.142.79:6391
      max-redirects: 3
    lettuce:
      pool:
        max-active: 1024 # 连接池最大连接数（默认为8，-1表示无限制 如果pool已经分配了超过max_active个jedis实例，则此时pool为耗尽）
        max-wait: 10000ms #最大等待连接时间，单位毫秒 默认为-1，表示永不超时，超时会抛出JedisConnectionException
        max-idle: 10
        min-idle: 5
      shutdown-timeout: 100ms
################Redis集群模式配置##############################################################
#############################################################################################
#############################################################################################
